sudo: required
language: python
dist: focal
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "nightly"
    - python: pypy
    - python: pypy3

install:
  - pip install .
  - pip install flask

script:
  - python setup.py test

notifications:
  email: false
