sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - "3.8-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3

install:
  - pip install .
  - pip install flask

script:
  - python setup.py test

notifications:
  email: false
